<?php

namespace ContainerCVPQxnx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N1TgpzTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n1TgpzT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n1TgpzT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'createDemoValidationDto' => ['privates', 'App\\Dto\\Request\\Demo\\CreateDemoValidationDto', 'getCreateDemoValidationDtoService', true],
        ], [
            'createDemoValidationDto' => 'App\\Dto\\Request\\Demo\\CreateDemoValidationDto',
        ]);
    }
}
