<?php

namespace ContainerCVPQxnx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateDemoValidationDtoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Dto\Request\Demo\CreateDemoValidationDto' shared autowired service.
     *
     * @return \App\Dto\Request\Demo\CreateDemoValidationDto
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Dto/Request/Demo/CreateDemoValidationDto.php';

        return $container->privates['App\\Dto\\Request\\Demo\\CreateDemoValidationDto'] = new \App\Dto\Request\Demo\CreateDemoValidationDto();
    }
}
