#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
  path: "%app.url.api.prefix%/auth/logout"
  methods: POST
  
#places_nearby:
#    path: "%app.url.api.prefix%/nearby-places"
#    controller: App\Controller\PlacesController::getNearbyPlaces
#    methods: GET