<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJa6XIpx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJa6XIpx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJa6XIpx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJa6XIpx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJa6XIpx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ja6XIpx',
    'container.build_id' => '8fbdf431',
    'container.build_time' => 1733133252,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJa6XIpx');
