<?php

namespace ContainerJa6XIpx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemoValidationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\DemoValidationController' shared autowired service.
     *
     * @return \App\Controller\DemoValidationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/DemoValidationController.php';

        $container->services['App\\Controller\\DemoValidationController'] = $instance = new \App\Controller\DemoValidationController();

        $instance->setContainer(($container->privates['.service_locator.2.N18_J'] ?? $container->load('get_ServiceLocator_2_N18JService'))->withContext('App\\Controller\\DemoValidationController', $container));

        return $instance;
    }
}
