<?php

namespace ContainerJa6XIpx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFindLocationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FindLocationController' shared autowired service.
     *
     * @return \App\Controller\FindLocationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/FindLocationController.php';

        return $container->services['App\\Controller\\FindLocationController'] = new \App\Controller\FindLocationController(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $container->getEnv('GOOGLE_MAPS_API_KEY'));
    }
}
