<?php

namespace ContainerJa6XIpx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSiretValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\SiretValidator' shared autowired service.
     *
     * @return \App\Validator\SiretValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Validator/SiretValidator.php';

        return $container->privates['App\\Validator\\SiretValidator'] = new \App\Validator\SiretValidator();
    }
}
