<?php

namespace ContainerJa6XIpx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateUserStatisticsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\UpdateUserStatisticsCommand' shared autowired service.
     *
     * @return \App\Command\UpdateUserStatisticsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/UpdateUserStatisticsCommand.php';

        $container->privates['App\\Command\\UpdateUserStatisticsCommand'] = $instance = new \App\Command\UpdateUserStatisticsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:update-user-statistics');

        return $instance;
    }
}
